// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: saving_advisor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SavingAdvisorService_HealthCheck_FullMethodName                  = "/saving_advisor.SavingAdvisorService/HealthCheck"
	SavingAdvisorService_GetUserPortfolio_FullMethodName             = "/saving_advisor.SavingAdvisorService/GetUserPortfolio"
	SavingAdvisorService_GetGeneralAnalysis_FullMethodName           = "/saving_advisor.SavingAdvisorService/GetGeneralAnalysis"
	SavingAdvisorService_GetRecommendationsPreview_FullMethodName    = "/saving_advisor.SavingAdvisorService/GetRecommendationsPreview"
	SavingAdvisorService_SubmitRecommendationFeedback_FullMethodName = "/saving_advisor.SavingAdvisorService/SubmitRecommendationFeedback"
	SavingAdvisorService_GetComprehensiveAnalysis_FullMethodName     = "/saving_advisor.SavingAdvisorService/GetComprehensiveAnalysis"
	SavingAdvisorService_GetVisualizationData_FullMethodName         = "/saving_advisor.SavingAdvisorService/GetVisualizationData"
	SavingAdvisorService_GetUserTasks_FullMethodName                 = "/saving_advisor.SavingAdvisorService/GetUserTasks"
	SavingAdvisorService_FinalizeSession_FullMethodName              = "/saving_advisor.SavingAdvisorService/FinalizeSession"
)

// SavingAdvisorServiceClient is the client API for SavingAdvisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 主要的Saving Advisorservice
type SavingAdvisorServiceClient interface {
	// health check
	HealthCheck(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// userasset相关
	GetUserPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioResponse, error)
	// analysis相关
	GetGeneralAnalysis(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	// recommendation相关
	GetRecommendationsPreview(ctx context.Context, in *RecommendationsPreviewRequest, opts ...grpc.CallOption) (*RecommendationsPreviewResponse, error)
	SubmitRecommendationFeedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
	GetComprehensiveAnalysis(ctx context.Context, in *ComprehensiveAnalysisRequest, opts ...grpc.CallOption) (*ComprehensiveAnalysisResponse, error)
	// 可视化相关
	GetVisualizationData(ctx context.Context, in *VisualizationRequest, opts ...grpc.CallOption) (*VisualizationResponse, error)
	// task相关
	GetUserTasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (*TasksResponse, error)
	// session管理
	FinalizeSession(ctx context.Context, in *SessionFinalizeRequest, opts ...grpc.CallOption) (*BaseResponse, error)
}

type savingAdvisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSavingAdvisorServiceClient(cc grpc.ClientConnInterface) SavingAdvisorServiceClient {
	return &savingAdvisorServiceClient{cc}
}

func (c *savingAdvisorServiceClient) HealthCheck(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) GetUserPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_GetUserPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) GetGeneralAnalysis(ctx context.Context, in *BaseRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_GetGeneralAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) GetRecommendationsPreview(ctx context.Context, in *RecommendationsPreviewRequest, opts ...grpc.CallOption) (*RecommendationsPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationsPreviewResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_GetRecommendationsPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) SubmitRecommendationFeedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedbackResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_SubmitRecommendationFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) GetComprehensiveAnalysis(ctx context.Context, in *ComprehensiveAnalysisRequest, opts ...grpc.CallOption) (*ComprehensiveAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComprehensiveAnalysisResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_GetComprehensiveAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) GetVisualizationData(ctx context.Context, in *VisualizationRequest, opts ...grpc.CallOption) (*VisualizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisualizationResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_GetVisualizationData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) GetUserTasks(ctx context.Context, in *TasksRequest, opts ...grpc.CallOption) (*TasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_GetUserTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *savingAdvisorServiceClient) FinalizeSession(ctx context.Context, in *SessionFinalizeRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, SavingAdvisorService_FinalizeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SavingAdvisorServiceServer is the server API for SavingAdvisorService service.
// All implementations must embed UnimplementedSavingAdvisorServiceServer
// for forward compatibility.
//
// 主要的Saving Advisorservice
type SavingAdvisorServiceServer interface {
	// health check
	HealthCheck(context.Context, *EmptyRequest) (*HealthResponse, error)
	// userasset相关
	GetUserPortfolio(context.Context, *PortfolioRequest) (*PortfolioResponse, error)
	// analysis相关
	GetGeneralAnalysis(context.Context, *BaseRequest) (*BaseResponse, error)
	// recommendation相关
	GetRecommendationsPreview(context.Context, *RecommendationsPreviewRequest) (*RecommendationsPreviewResponse, error)
	SubmitRecommendationFeedback(context.Context, *FeedbackRequest) (*FeedbackResponse, error)
	GetComprehensiveAnalysis(context.Context, *ComprehensiveAnalysisRequest) (*ComprehensiveAnalysisResponse, error)
	// 可视化相关
	GetVisualizationData(context.Context, *VisualizationRequest) (*VisualizationResponse, error)
	// task相关
	GetUserTasks(context.Context, *TasksRequest) (*TasksResponse, error)
	// session管理
	FinalizeSession(context.Context, *SessionFinalizeRequest) (*BaseResponse, error)
	mustEmbedUnimplementedSavingAdvisorServiceServer()
}

// UnimplementedSavingAdvisorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSavingAdvisorServiceServer struct{}

func (UnimplementedSavingAdvisorServiceServer) HealthCheck(context.Context, *EmptyRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) GetUserPortfolio(context.Context, *PortfolioRequest) (*PortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPortfolio not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) GetGeneralAnalysis(context.Context, *BaseRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeneralAnalysis not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) GetRecommendationsPreview(context.Context, *RecommendationsPreviewRequest) (*RecommendationsPreviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendationsPreview not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) SubmitRecommendationFeedback(context.Context, *FeedbackRequest) (*FeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRecommendationFeedback not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) GetComprehensiveAnalysis(context.Context, *ComprehensiveAnalysisRequest) (*ComprehensiveAnalysisResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComprehensiveAnalysis not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) GetVisualizationData(context.Context, *VisualizationRequest) (*VisualizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisualizationData not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) GetUserTasks(context.Context, *TasksRequest) (*TasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTasks not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) FinalizeSession(context.Context, *SessionFinalizeRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeSession not implemented")
}
func (UnimplementedSavingAdvisorServiceServer) mustEmbedUnimplementedSavingAdvisorServiceServer() {}
func (UnimplementedSavingAdvisorServiceServer) testEmbeddedByValue()                              {}

// UnsafeSavingAdvisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SavingAdvisorServiceServer will
// result in compilation errors.
type UnsafeSavingAdvisorServiceServer interface {
	mustEmbedUnimplementedSavingAdvisorServiceServer()
}

func RegisterSavingAdvisorServiceServer(s grpc.ServiceRegistrar, srv SavingAdvisorServiceServer) {
	// If the following call pancis, it indicates UnimplementedSavingAdvisorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SavingAdvisorService_ServiceDesc, srv)
}

func _SavingAdvisorService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).HealthCheck(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_GetUserPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).GetUserPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_GetUserPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).GetUserPortfolio(ctx, req.(*PortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_GetGeneralAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).GetGeneralAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_GetGeneralAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).GetGeneralAnalysis(ctx, req.(*BaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_GetRecommendationsPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationsPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).GetRecommendationsPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_GetRecommendationsPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).GetRecommendationsPreview(ctx, req.(*RecommendationsPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_SubmitRecommendationFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).SubmitRecommendationFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_SubmitRecommendationFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).SubmitRecommendationFeedback(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_GetComprehensiveAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComprehensiveAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).GetComprehensiveAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_GetComprehensiveAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).GetComprehensiveAnalysis(ctx, req.(*ComprehensiveAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_GetVisualizationData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisualizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).GetVisualizationData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_GetVisualizationData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).GetVisualizationData(ctx, req.(*VisualizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_GetUserTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).GetUserTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_GetUserTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).GetUserTasks(ctx, req.(*TasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SavingAdvisorService_FinalizeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionFinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SavingAdvisorServiceServer).FinalizeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SavingAdvisorService_FinalizeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SavingAdvisorServiceServer).FinalizeSession(ctx, req.(*SessionFinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SavingAdvisorService_ServiceDesc is the grpc.ServiceDesc for SavingAdvisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SavingAdvisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saving_advisor.SavingAdvisorService",
	HandlerType: (*SavingAdvisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _SavingAdvisorService_HealthCheck_Handler,
		},
		{
			MethodName: "GetUserPortfolio",
			Handler:    _SavingAdvisorService_GetUserPortfolio_Handler,
		},
		{
			MethodName: "GetGeneralAnalysis",
			Handler:    _SavingAdvisorService_GetGeneralAnalysis_Handler,
		},
		{
			MethodName: "GetRecommendationsPreview",
			Handler:    _SavingAdvisorService_GetRecommendationsPreview_Handler,
		},
		{
			MethodName: "SubmitRecommendationFeedback",
			Handler:    _SavingAdvisorService_SubmitRecommendationFeedback_Handler,
		},
		{
			MethodName: "GetComprehensiveAnalysis",
			Handler:    _SavingAdvisorService_GetComprehensiveAnalysis_Handler,
		},
		{
			MethodName: "GetVisualizationData",
			Handler:    _SavingAdvisorService_GetVisualizationData_Handler,
		},
		{
			MethodName: "GetUserTasks",
			Handler:    _SavingAdvisorService_GetUserTasks_Handler,
		},
		{
			MethodName: "FinalizeSession",
			Handler:    _SavingAdvisorService_FinalizeSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saving_advisor.proto",
}
