// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: saving_advisor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// userassetinfo
type UserAsset struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AssetType        string                 `protobuf:"bytes,1,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	CurrentValue     float64                `protobuf:"fixed64,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	TargetAllocation float64                `protobuf:"fixed64,3,opt,name=target_allocation,json=targetAllocation,proto3" json:"target_allocation,omitempty"`
	LastUpdated      string                 `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserAsset) Reset() {
	*x = UserAsset{}
	mi := &file_saving_advisor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAsset) ProtoMessage() {}

func (x *UserAsset) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAsset.ProtoReflect.Descriptor instead.
func (*UserAsset) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{0}
}

func (x *UserAsset) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *UserAsset) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *UserAsset) GetTargetAllocation() float64 {
	if x != nil {
		return x.TargetAllocation
	}
	return 0
}

func (x *UserAsset) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

// userportfolio
type UserPortfolio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Assets        []*UserAsset           `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	TotalValue    float64                `protobuf:"fixed64,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	LastUpdated   string                 `protobuf:"bytes,4,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPortfolio) Reset() {
	*x = UserPortfolio{}
	mi := &file_saving_advisor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPortfolio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPortfolio) ProtoMessage() {}

func (x *UserPortfolio) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPortfolio.ProtoReflect.Descriptor instead.
func (*UserPortfolio) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{1}
}

func (x *UserPortfolio) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPortfolio) GetAssets() []*UserAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *UserPortfolio) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *UserPortfolio) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

// recommendationinfo
type Recommendation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendationId string                 `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AssetType        string                 `protobuf:"bytes,4,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	PotentialGain    float64                `protobuf:"fixed64,5,opt,name=potential_gain,json=potentialGain,proto3" json:"potential_gain,omitempty"`
	AgentName        string                 `protobuf:"bytes,6,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Priority         int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_saving_advisor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{2}
}

func (x *Recommendation) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *Recommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recommendation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recommendation) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *Recommendation) GetPotentialGain() float64 {
	if x != nil {
		return x.PotentialGain
	}
	return 0
}

func (x *Recommendation) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *Recommendation) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// 多代理recommendationresponse
type MultiAgentRecommendations struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Analyses          []*AgentAnalysis       `protobuf:"bytes,2,rep,name=analyses,proto3" json:"analyses,omitempty"`
	OverallAssessment string                 `protobuf:"bytes,3,opt,name=overall_assessment,json=overallAssessment,proto3" json:"overall_assessment,omitempty"`
	Timestamp         string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MultiAgentRecommendations) Reset() {
	*x = MultiAgentRecommendations{}
	mi := &file_saving_advisor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiAgentRecommendations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiAgentRecommendations) ProtoMessage() {}

func (x *MultiAgentRecommendations) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiAgentRecommendations.ProtoReflect.Descriptor instead.
func (*MultiAgentRecommendations) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{3}
}

func (x *MultiAgentRecommendations) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MultiAgentRecommendations) GetAnalyses() []*AgentAnalysis {
	if x != nil {
		return x.Analyses
	}
	return nil
}

func (x *MultiAgentRecommendations) GetOverallAssessment() string {
	if x != nil {
		return x.OverallAssessment
	}
	return ""
}

func (x *MultiAgentRecommendations) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 代理analysis result
type AgentAnalysis struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentName       string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	AssetType       string                 `protobuf:"bytes,2,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	Findings        string                 `protobuf:"bytes,3,opt,name=findings,proto3" json:"findings,omitempty"`
	Recommendations []*Recommendation      `protobuf:"bytes,4,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentAnalysis) Reset() {
	*x = AgentAnalysis{}
	mi := &file_saving_advisor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAnalysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAnalysis) ProtoMessage() {}

func (x *AgentAnalysis) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAnalysis.ProtoReflect.Descriptor instead.
func (*AgentAnalysis) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{4}
}

func (x *AgentAnalysis) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentAnalysis) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *AgentAnalysis) GetFindings() string {
	if x != nil {
		return x.Findings
	}
	return ""
}

func (x *AgentAnalysis) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// feedbackrequest
type FeedbackRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecommendationId string                 `protobuf:"bytes,2,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                          // "accepted", "rejected"
	RejectionReason  string                 `protobuf:"bytes,4,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"` // 可选
	RejectionDetail  string                 `protobuf:"bytes,5,opt,name=rejection_detail,json=rejectionDetail,proto3" json:"rejection_detail,omitempty"` // 可选
	AgentName        string                 `protobuf:"bytes,6,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`                   // 可选
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeedbackRequest) Reset() {
	*x = FeedbackRequest{}
	mi := &file_saving_advisor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackRequest) ProtoMessage() {}

func (x *FeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackRequest.ProtoReflect.Descriptor instead.
func (*FeedbackRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{5}
}

func (x *FeedbackRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedbackRequest) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *FeedbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FeedbackRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *FeedbackRequest) GetRejectionDetail() string {
	if x != nil {
		return x.RejectionDetail
	}
	return ""
}

func (x *FeedbackRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

// 可视化data
type VisualizationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChartType     string                 `protobuf:"bytes,1,opt,name=chart_type,json=chartType,proto3" json:"chart_type,omitempty"`
	Data          map[string]float64     `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	TotalValue    float64                `protobuf:"fixed64,3,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualizationData) Reset() {
	*x = VisualizationData{}
	mi := &file_saving_advisor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizationData) ProtoMessage() {}

func (x *VisualizationData) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizationData.ProtoReflect.Descriptor instead.
func (*VisualizationData) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{6}
}

func (x *VisualizationData) GetChartType() string {
	if x != nil {
		return x.ChartType
	}
	return ""
}

func (x *VisualizationData) GetData() map[string]float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VisualizationData) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *VisualizationData) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// taskinfo
type Task struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DueDate          string                 `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	CompletionReward float64                `protobuf:"fixed64,5,opt,name=completion_reward,json=completionReward,proto3" json:"completion_reward,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_saving_advisor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{7}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *Task) GetCompletionReward() float64 {
	if x != nil {
		return x.CompletionReward
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 综合analysisrequest
type ComprehensiveAnalysisRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	UserId                    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AcceptedRecommendationIds []string               `protobuf:"bytes,2,rep,name=accepted_recommendation_ids,json=acceptedRecommendationIds,proto3" json:"accepted_recommendation_ids,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ComprehensiveAnalysisRequest) Reset() {
	*x = ComprehensiveAnalysisRequest{}
	mi := &file_saving_advisor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComprehensiveAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComprehensiveAnalysisRequest) ProtoMessage() {}

func (x *ComprehensiveAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComprehensiveAnalysisRequest.ProtoReflect.Descriptor instead.
func (*ComprehensiveAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{8}
}

func (x *ComprehensiveAnalysisRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ComprehensiveAnalysisRequest) GetAcceptedRecommendationIds() []string {
	if x != nil {
		return x.AcceptedRecommendationIds
	}
	return nil
}

// 综合analysisresponse
type ComprehensiveAnalysisResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ComprehensiveSummary string                 `protobuf:"bytes,2,opt,name=comprehensive_summary,json=comprehensiveSummary,proto3" json:"comprehensive_summary,omitempty"`
	InitialAssets        float64                `protobuf:"fixed64,3,opt,name=initial_assets,json=initialAssets,proto3" json:"initial_assets,omitempty"`
	PredictedAssets      float64                `protobuf:"fixed64,4,opt,name=predicted_assets,json=predictedAssets,proto3" json:"predicted_assets,omitempty"`
	Timestamp            string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Success              bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage         string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ComprehensiveAnalysisResponse) Reset() {
	*x = ComprehensiveAnalysisResponse{}
	mi := &file_saving_advisor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComprehensiveAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComprehensiveAnalysisResponse) ProtoMessage() {}

func (x *ComprehensiveAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComprehensiveAnalysisResponse.ProtoReflect.Descriptor instead.
func (*ComprehensiveAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{9}
}

func (x *ComprehensiveAnalysisResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ComprehensiveAnalysisResponse) GetComprehensiveSummary() string {
	if x != nil {
		return x.ComprehensiveSummary
	}
	return ""
}

func (x *ComprehensiveAnalysisResponse) GetInitialAssets() float64 {
	if x != nil {
		return x.InitialAssets
	}
	return 0
}

func (x *ComprehensiveAnalysisResponse) GetPredictedAssets() float64 {
	if x != nil {
		return x.PredictedAssets
	}
	return 0
}

func (x *ComprehensiveAnalysisResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ComprehensiveAnalysisResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ComprehensiveAnalysisResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 基础request
type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_saving_advisor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{10}
}

func (x *BaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 基础response
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_saving_advisor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{11}
}

func (x *BaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BaseResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *BaseResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// usercombinerequest
type PortfolioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioRequest) Reset() {
	*x = PortfolioRequest{}
	mi := &file_saving_advisor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioRequest) ProtoMessage() {}

func (x *PortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioRequest.ProtoReflect.Descriptor instead.
func (*PortfolioRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{12}
}

func (x *PortfolioRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// usercombineresponse
type PortfolioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Portfolio     *UserPortfolio         `protobuf:"bytes,1,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioResponse) Reset() {
	*x = PortfolioResponse{}
	mi := &file_saving_advisor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioResponse) ProtoMessage() {}

func (x *PortfolioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioResponse.ProtoReflect.Descriptor instead.
func (*PortfolioResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{13}
}

func (x *PortfolioResponse) GetPortfolio() *UserPortfolio {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

func (x *PortfolioResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PortfolioResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PortfolioResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// recommendation预览request
type RecommendationsPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ForceFresh    bool                   `protobuf:"varint,2,opt,name=force_fresh,json=forceFresh,proto3" json:"force_fresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationsPreviewRequest) Reset() {
	*x = RecommendationsPreviewRequest{}
	mi := &file_saving_advisor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsPreviewRequest) ProtoMessage() {}

func (x *RecommendationsPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsPreviewRequest.ProtoReflect.Descriptor instead.
func (*RecommendationsPreviewRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{14}
}

func (x *RecommendationsPreviewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationsPreviewRequest) GetForceFresh() bool {
	if x != nil {
		return x.ForceFresh
	}
	return false
}

// recommendation预览response
type RecommendationsPreviewResponse struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Recommendations *MultiAgentRecommendations `protobuf:"bytes,1,opt,name=recommendations,proto3" json:"recommendations,omitempty"`
	Success         bool                       `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                     `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp       string                     `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendationsPreviewResponse) Reset() {
	*x = RecommendationsPreviewResponse{}
	mi := &file_saving_advisor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsPreviewResponse) ProtoMessage() {}

func (x *RecommendationsPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsPreviewResponse.ProtoReflect.Descriptor instead.
func (*RecommendationsPreviewResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{15}
}

func (x *RecommendationsPreviewResponse) GetRecommendations() *MultiAgentRecommendations {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *RecommendationsPreviewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecommendationsPreviewResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RecommendationsPreviewResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// feedbackresponse
type FeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackResponse) Reset() {
	*x = FeedbackResponse{}
	mi := &file_saving_advisor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackResponse) ProtoMessage() {}

func (x *FeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackResponse.ProtoReflect.Descriptor instead.
func (*FeedbackResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{16}
}

func (x *FeedbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FeedbackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FeedbackResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FeedbackResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 可视化request
type VisualizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChartType     string                 `protobuf:"bytes,2,opt,name=chart_type,json=chartType,proto3" json:"chart_type,omitempty"` // "pie", "bar"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualizationRequest) Reset() {
	*x = VisualizationRequest{}
	mi := &file_saving_advisor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizationRequest) ProtoMessage() {}

func (x *VisualizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizationRequest.ProtoReflect.Descriptor instead.
func (*VisualizationRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{17}
}

func (x *VisualizationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VisualizationRequest) GetChartType() string {
	if x != nil {
		return x.ChartType
	}
	return ""
}

// 可视化response
type VisualizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *VisualizationData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualizationResponse) Reset() {
	*x = VisualizationResponse{}
	mi := &file_saving_advisor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizationResponse) ProtoMessage() {}

func (x *VisualizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizationResponse.ProtoReflect.Descriptor instead.
func (*VisualizationResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{18}
}

func (x *VisualizationResponse) GetData() *VisualizationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VisualizationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VisualizationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *VisualizationResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// tasklistrequest
type TasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimePeriod    string                 `protobuf:"bytes,2,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"` // "monthly", "weekly"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksRequest) Reset() {
	*x = TasksRequest{}
	mi := &file_saving_advisor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksRequest) ProtoMessage() {}

func (x *TasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksRequest.ProtoReflect.Descriptor instead.
func (*TasksRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{19}
}

func (x *TasksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TasksRequest) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

// tasklistresponse
type TasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksResponse) Reset() {
	*x = TasksResponse{}
	mi := &file_saving_advisor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksResponse) ProtoMessage() {}

func (x *TasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksResponse.ProtoReflect.Descriptor instead.
func (*TasksResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{20}
}

func (x *TasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TasksResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TasksResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TasksResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// sessioncompleterequest
type SessionFinalizeRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	UserId           string                   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Feedback         map[string]*FeedbackData `protobuf:"bytes,2,rep,name=feedback,proto3" json:"feedback,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionType      string                   `protobuf:"bytes,3,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	InputData        string                   `protobuf:"bytes,4,opt,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`    // JSON格式
	AiResponse       string                   `protobuf:"bytes,5,opt,name=ai_response,json=aiResponse,proto3" json:"ai_response,omitempty"` // JSON格式
	ProcessingTimeMs int64                    `protobuf:"varint,6,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionFinalizeRequest) Reset() {
	*x = SessionFinalizeRequest{}
	mi := &file_saving_advisor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionFinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionFinalizeRequest) ProtoMessage() {}

func (x *SessionFinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionFinalizeRequest.ProtoReflect.Descriptor instead.
func (*SessionFinalizeRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{21}
}

func (x *SessionFinalizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionFinalizeRequest) GetFeedback() map[string]*FeedbackData {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *SessionFinalizeRequest) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *SessionFinalizeRequest) GetInputData() string {
	if x != nil {
		return x.InputData
	}
	return ""
}

func (x *SessionFinalizeRequest) GetAiResponse() string {
	if x != nil {
		return x.AiResponse
	}
	return ""
}

func (x *SessionFinalizeRequest) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

// feedbackdata
type FeedbackData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	RejectionReason string                 `protobuf:"bytes,3,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FeedbackData) Reset() {
	*x = FeedbackData{}
	mi := &file_saving_advisor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackData) ProtoMessage() {}

func (x *FeedbackData) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackData.ProtoReflect.Descriptor instead.
func (*FeedbackData) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{22}
}

func (x *FeedbackData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedbackData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FeedbackData) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

// health checkresponse
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_saving_advisor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{23}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 空request（用于health check等）
type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_saving_advisor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saving_advisor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_saving_advisor_proto_rawDescGZIP(), []int{24}
}

var File_saving_advisor_proto protoreflect.FileDescriptor

const file_saving_advisor_proto_rawDesc = "" +
	"\n" +
	"\x14saving_advisor.proto\x12\x0esaving_advisor\"\x9f\x01\n" +
	"\tUserAsset\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x01 \x01(\tR\tassetType\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\x01R\fcurrentValue\x12+\n" +
	"\x11target_allocation\x18\x03 \x01(\x01R\x10targetAllocation\x12!\n" +
	"\flast_updated\x18\x04 \x01(\tR\vlastUpdated\"\x9f\x01\n" +
	"\rUserPortfolio\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x121\n" +
	"\x06assets\x18\x02 \x03(\v2\x19.saving_advisor.UserAssetR\x06assets\x12\x1f\n" +
	"\vtotal_value\x18\x03 \x01(\x01R\n" +
	"totalValue\x12!\n" +
	"\flast_updated\x18\x04 \x01(\tR\vlastUpdated\"\xf6\x01\n" +
	"\x0eRecommendation\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x04 \x01(\tR\tassetType\x12%\n" +
	"\x0epotential_gain\x18\x05 \x01(\x01R\rpotentialGain\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x06 \x01(\tR\tagentName\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\"\xbc\x01\n" +
	"\x19MultiAgentRecommendations\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\banalyses\x18\x02 \x03(\v2\x1d.saving_advisor.AgentAnalysisR\banalyses\x12-\n" +
	"\x12overall_assessment\x18\x03 \x01(\tR\x11overallAssessment\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xb3\x01\n" +
	"\rAgentAnalysis\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\tR\tassetType\x12\x1a\n" +
	"\bfindings\x18\x03 \x01(\tR\bfindings\x12H\n" +
	"\x0frecommendations\x18\x04 \x03(\v2\x1e.saving_advisor.RecommendationR\x0frecommendations\"\xe4\x01\n" +
	"\x0fFeedbackRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11recommendation_id\x18\x02 \x01(\tR\x10recommendationId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12)\n" +
	"\x10rejection_reason\x18\x04 \x01(\tR\x0frejectionReason\x12)\n" +
	"\x10rejection_detail\x18\x05 \x01(\tR\x0frejectionDetail\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x06 \x01(\tR\tagentName\"\xeb\x01\n" +
	"\x11VisualizationData\x12\x1d\n" +
	"\n" +
	"chart_type\x18\x01 \x01(\tR\tchartType\x12?\n" +
	"\x04data\x18\x02 \x03(\v2+.saving_advisor.VisualizationData.DataEntryR\x04data\x12\x1f\n" +
	"\vtotal_value\x18\x03 \x01(\x01R\n" +
	"totalValue\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb7\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bdue_date\x18\x04 \x01(\tR\adueDate\x12+\n" +
	"\x11completion_reward\x18\x05 \x01(\x01R\x10completionReward\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"w\n" +
	"\x1cComprehensiveAnalysisRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12>\n" +
	"\x1baccepted_recommendation_ids\x18\x02 \x03(\tR\x19acceptedRecommendationIds\"\x9c\x02\n" +
	"\x1dComprehensiveAnalysisResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x15comprehensive_summary\x18\x02 \x01(\tR\x14comprehensiveSummary\x12%\n" +
	"\x0einitial_assets\x18\x03 \x01(\x01R\rinitialAssets\x12)\n" +
	"\x10predicted_assets\x18\x04 \x01(\x01R\x0fpredictedAssets\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"&\n" +
	"\vBaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x85\x01\n" +
	"\fBaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"+\n" +
	"\x10PortfolioRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xad\x01\n" +
	"\x11PortfolioResponse\x12;\n" +
	"\tportfolio\x18\x01 \x01(\v2\x1d.saving_advisor.UserPortfolioR\tportfolio\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"Y\n" +
	"\x1dRecommendationsPreviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vforce_fresh\x18\x02 \x01(\bR\n" +
	"forceFresh\"\xd2\x01\n" +
	"\x1eRecommendationsPreviewResponse\x12S\n" +
	"\x0frecommendations\x18\x01 \x01(\v2).saving_advisor.MultiAgentRecommendationsR\x0frecommendations\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\x89\x01\n" +
	"\x10FeedbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"N\n" +
	"\x14VisualizationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"chart_type\x18\x02 \x01(\tR\tchartType\"\xab\x01\n" +
	"\x15VisualizationResponse\x125\n" +
	"\x04data\x18\x01 \x01(\v2!.saving_advisor.VisualizationDataR\x04data\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"H\n" +
	"\fTasksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtime_period\x18\x02 \x01(\tR\n" +
	"timePeriod\"\x98\x01\n" +
	"\rTasksResponse\x12*\n" +
	"\x05tasks\x18\x01 \x03(\v2\x14.saving_advisor.TaskR\x05tasks\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xef\x02\n" +
	"\x16SessionFinalizeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12P\n" +
	"\bfeedback\x18\x02 \x03(\v24.saving_advisor.SessionFinalizeRequest.FeedbackEntryR\bfeedback\x12!\n" +
	"\fsession_type\x18\x03 \x01(\tR\vsessionType\x12\x1d\n" +
	"\n" +
	"input_data\x18\x04 \x01(\tR\tinputData\x12\x1f\n" +
	"\vai_response\x18\x05 \x01(\tR\n" +
	"aiResponse\x12,\n" +
	"\x12processing_time_ms\x18\x06 \x01(\x03R\x10processingTimeMs\x1aY\n" +
	"\rFeedbackEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.saving_advisor.FeedbackDataR\x05value:\x028\x01\"g\n" +
	"\fFeedbackData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12)\n" +
	"\x10rejection_reason\x18\x03 \x01(\tR\x0frejectionReason\"z\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\x0e\n" +
	"\fEmptyRequest2\xf0\x06\n" +
	"\x14SavingAdvisorService\x12K\n" +
	"\vHealthCheck\x12\x1c.saving_advisor.EmptyRequest\x1a\x1e.saving_advisor.HealthResponse\x12W\n" +
	"\x10GetUserPortfolio\x12 .saving_advisor.PortfolioRequest\x1a!.saving_advisor.PortfolioResponse\x12O\n" +
	"\x12GetGeneralAnalysis\x12\x1b.saving_advisor.BaseRequest\x1a\x1c.saving_advisor.BaseResponse\x12z\n" +
	"\x19GetRecommendationsPreview\x12-.saving_advisor.RecommendationsPreviewRequest\x1a..saving_advisor.RecommendationsPreviewResponse\x12a\n" +
	"\x1cSubmitRecommendationFeedback\x12\x1f.saving_advisor.FeedbackRequest\x1a .saving_advisor.FeedbackResponse\x12w\n" +
	"\x18GetComprehensiveAnalysis\x12,.saving_advisor.ComprehensiveAnalysisRequest\x1a-.saving_advisor.ComprehensiveAnalysisResponse\x12c\n" +
	"\x14GetVisualizationData\x12$.saving_advisor.VisualizationRequest\x1a%.saving_advisor.VisualizationResponse\x12K\n" +
	"\fGetUserTasks\x12\x1c.saving_advisor.TasksRequest\x1a\x1d.saving_advisor.TasksResponse\x12W\n" +
	"\x0fFinalizeSession\x12&.saving_advisor.SessionFinalizeRequest\x1a\x1c.saving_advisor.BaseResponseb\x06proto3"

var (
	file_saving_advisor_proto_rawDescOnce sync.Once
	file_saving_advisor_proto_rawDescData []byte
)

func file_saving_advisor_proto_rawDescGZIP() []byte {
	file_saving_advisor_proto_rawDescOnce.Do(func() {
		file_saving_advisor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saving_advisor_proto_rawDesc), len(file_saving_advisor_proto_rawDesc)))
	})
	return file_saving_advisor_proto_rawDescData
}

var file_saving_advisor_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_saving_advisor_proto_goTypes = []any{
	(*UserAsset)(nil),                      // 0: saving_advisor.UserAsset
	(*UserPortfolio)(nil),                  // 1: saving_advisor.UserPortfolio
	(*Recommendation)(nil),                 // 2: saving_advisor.Recommendation
	(*MultiAgentRecommendations)(nil),      // 3: saving_advisor.MultiAgentRecommendations
	(*AgentAnalysis)(nil),                  // 4: saving_advisor.AgentAnalysis
	(*FeedbackRequest)(nil),                // 5: saving_advisor.FeedbackRequest
	(*VisualizationData)(nil),              // 6: saving_advisor.VisualizationData
	(*Task)(nil),                           // 7: saving_advisor.Task
	(*ComprehensiveAnalysisRequest)(nil),   // 8: saving_advisor.ComprehensiveAnalysisRequest
	(*ComprehensiveAnalysisResponse)(nil),  // 9: saving_advisor.ComprehensiveAnalysisResponse
	(*BaseRequest)(nil),                    // 10: saving_advisor.BaseRequest
	(*BaseResponse)(nil),                   // 11: saving_advisor.BaseResponse
	(*PortfolioRequest)(nil),               // 12: saving_advisor.PortfolioRequest
	(*PortfolioResponse)(nil),              // 13: saving_advisor.PortfolioResponse
	(*RecommendationsPreviewRequest)(nil),  // 14: saving_advisor.RecommendationsPreviewRequest
	(*RecommendationsPreviewResponse)(nil), // 15: saving_advisor.RecommendationsPreviewResponse
	(*FeedbackResponse)(nil),               // 16: saving_advisor.FeedbackResponse
	(*VisualizationRequest)(nil),           // 17: saving_advisor.VisualizationRequest
	(*VisualizationResponse)(nil),          // 18: saving_advisor.VisualizationResponse
	(*TasksRequest)(nil),                   // 19: saving_advisor.TasksRequest
	(*TasksResponse)(nil),                  // 20: saving_advisor.TasksResponse
	(*SessionFinalizeRequest)(nil),         // 21: saving_advisor.SessionFinalizeRequest
	(*FeedbackData)(nil),                   // 22: saving_advisor.FeedbackData
	(*HealthResponse)(nil),                 // 23: saving_advisor.HealthResponse
	(*EmptyRequest)(nil),                   // 24: saving_advisor.EmptyRequest
	nil,                                    // 25: saving_advisor.VisualizationData.DataEntry
	nil,                                    // 26: saving_advisor.SessionFinalizeRequest.FeedbackEntry
}
var file_saving_advisor_proto_depIdxs = []int32{
	0,  // 0: saving_advisor.UserPortfolio.assets:type_name -> saving_advisor.UserAsset
	4,  // 1: saving_advisor.MultiAgentRecommendations.analyses:type_name -> saving_advisor.AgentAnalysis
	2,  // 2: saving_advisor.AgentAnalysis.recommendations:type_name -> saving_advisor.Recommendation
	25, // 3: saving_advisor.VisualizationData.data:type_name -> saving_advisor.VisualizationData.DataEntry
	1,  // 4: saving_advisor.PortfolioResponse.portfolio:type_name -> saving_advisor.UserPortfolio
	3,  // 5: saving_advisor.RecommendationsPreviewResponse.recommendations:type_name -> saving_advisor.MultiAgentRecommendations
	6,  // 6: saving_advisor.VisualizationResponse.data:type_name -> saving_advisor.VisualizationData
	7,  // 7: saving_advisor.TasksResponse.tasks:type_name -> saving_advisor.Task
	26, // 8: saving_advisor.SessionFinalizeRequest.feedback:type_name -> saving_advisor.SessionFinalizeRequest.FeedbackEntry
	22, // 9: saving_advisor.SessionFinalizeRequest.FeedbackEntry.value:type_name -> saving_advisor.FeedbackData
	24, // 10: saving_advisor.SavingAdvisorService.HealthCheck:input_type -> saving_advisor.EmptyRequest
	12, // 11: saving_advisor.SavingAdvisorService.GetUserPortfolio:input_type -> saving_advisor.PortfolioRequest
	10, // 12: saving_advisor.SavingAdvisorService.GetGeneralAnalysis:input_type -> saving_advisor.BaseRequest
	14, // 13: saving_advisor.SavingAdvisorService.GetRecommendationsPreview:input_type -> saving_advisor.RecommendationsPreviewRequest
	5,  // 14: saving_advisor.SavingAdvisorService.SubmitRecommendationFeedback:input_type -> saving_advisor.FeedbackRequest
	8,  // 15: saving_advisor.SavingAdvisorService.GetComprehensiveAnalysis:input_type -> saving_advisor.ComprehensiveAnalysisRequest
	17, // 16: saving_advisor.SavingAdvisorService.GetVisualizationData:input_type -> saving_advisor.VisualizationRequest
	19, // 17: saving_advisor.SavingAdvisorService.GetUserTasks:input_type -> saving_advisor.TasksRequest
	21, // 18: saving_advisor.SavingAdvisorService.FinalizeSession:input_type -> saving_advisor.SessionFinalizeRequest
	23, // 19: saving_advisor.SavingAdvisorService.HealthCheck:output_type -> saving_advisor.HealthResponse
	13, // 20: saving_advisor.SavingAdvisorService.GetUserPortfolio:output_type -> saving_advisor.PortfolioResponse
	11, // 21: saving_advisor.SavingAdvisorService.GetGeneralAnalysis:output_type -> saving_advisor.BaseResponse
	15, // 22: saving_advisor.SavingAdvisorService.GetRecommendationsPreview:output_type -> saving_advisor.RecommendationsPreviewResponse
	16, // 23: saving_advisor.SavingAdvisorService.SubmitRecommendationFeedback:output_type -> saving_advisor.FeedbackResponse
	9,  // 24: saving_advisor.SavingAdvisorService.GetComprehensiveAnalysis:output_type -> saving_advisor.ComprehensiveAnalysisResponse
	18, // 25: saving_advisor.SavingAdvisorService.GetVisualizationData:output_type -> saving_advisor.VisualizationResponse
	20, // 26: saving_advisor.SavingAdvisorService.GetUserTasks:output_type -> saving_advisor.TasksResponse
	11, // 27: saving_advisor.SavingAdvisorService.FinalizeSession:output_type -> saving_advisor.BaseResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_saving_advisor_proto_init() }
func file_saving_advisor_proto_init() {
	if File_saving_advisor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saving_advisor_proto_rawDesc), len(file_saving_advisor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saving_advisor_proto_goTypes,
		DependencyIndexes: file_saving_advisor_proto_depIdxs,
		MessageInfos:      file_saving_advisor_proto_msgTypes,
	}.Build()
	File_saving_advisor_proto = out.File
	file_saving_advisor_proto_goTypes = nil
	file_saving_advisor_proto_depIdxs = nil
}
